### ISSUE TITLE
AbellS1063 missing images.

### ISSUE THREAD

**Issue by VasilyKokorev** [dawn-cph/alcs-clusters#4]
A part of S1063 (and some other fields as well?) field is lacking the HST/ACS and WFC images, except for F125W.

**Comment by gbrammer** [comment]
@VasilyKokorev Is that the case for both the combined ``hff-`` field and the cluster-only field?

**Comment by VasilyKokorev** [comment]
@gbrammer it seems fine for the cluster only field, perhaps Seiji was referring to the missing stuff from the BUFFALO area
